//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalyzerApp.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UltimateChartistStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UltimateChartistStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockAnalyzerApp.Localisation.UltimateChartistStrings", typeof(UltimateChartistStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name contains some invalid charaters &apos;!&quot;%*(){}[]?\&lt;&gt;.
        /// </summary>
        internal static string Dlg_InvalidCarater {
            get {
                return ResourceManager.GetString("Dlg_InvalidCarater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate Chartist will restart to take your change into account..
        /// </summary>
        internal static string DlgContent_NeedToRestart {
            get {
                return ResourceManager.GetString("DlgContent_NeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string DlgTitle_InvalidInput {
            get {
                return ResourceManager.GetString("DlgTitle_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Restart.
        /// </summary>
        internal static string DlgTitle_NeedToRestart {
            get {
                return ResourceManager.GetString("DlgTitle_NeedToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License file is corrupted, please check your username in the preference dialog, and get a new license file.
        ///If the problem persists, please contact Ultimate Chartist support team..
        /// </summary>
        internal static string LicenseCorrupted {
            get {
                return ResourceManager.GetString("LicenseCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your license has expired, please visit www.ultimatechartist.com to renew it, and then use the option dialog to download it..
        /// </summary>
        internal static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license in not for this machine, please get a valid license at www.ultimatechartist.com and download it using the options window..
        /// </summary>
        internal static string LicenseInvalidMachineId {
            get {
                return ResourceManager.GetString("LicenseInvalidMachineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license in not for the user defined in the preferences..
        /// </summary>
        internal static string LicenseInvalidUserId {
            get {
                return ResourceManager.GetString("LicenseInvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no licence file on your installation, please get a valid license from www.ultimatechartist.com and then download it from the option window..
        /// </summary>
        internal static string LicenseNoFile {
            get {
                return ResourceManager.GetString("LicenseNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license is for an older version of Ultimate Chartist. Either revert to previous version or get a valid license from www.ultimatechartist.com.
        /// </summary>
        internal static string LicenseWrongVersion {
            get {
                return ResourceManager.GetString("LicenseWrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The setup of Ultimate Chartist is coprrupted, please reinstall the application.
        ///If the problem persist, contact Ultimate Chartist support team..
        /// </summary>
        internal static string SetupCorruptedText {
            get {
                return ResourceManager.GetString("SetupCorruptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Corrupted.
        /// </summary>
        internal static string SetupCorruptedTitle {
            get {
                return ResourceManager.GetString("SetupCorruptedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to void.
        /// </summary>
        internal static string ThemeEmpty {
            get {
                return ResourceManager.GetString("ThemeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.ultimatechartist.com.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
    }
}
