//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalyzerApp.Properties
{


   /// <summary>
   ///   A strongly-typed resource class, for looking up localized strings, etc.
   /// </summary>
   // This class was auto-generated by the StronglyTypedResourceBuilder
   // class via a tool like ResGen or Visual Studio.
   // To add or remove a member, edit your .ResX file then rerun ResGen
   // with the /str option, or rebuild your VS project.
   [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
   [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
   [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
   internal class Resources
   {

      private static global::System.Resources.ResourceManager resourceMan;

      private static global::System.Globalization.CultureInfo resourceCulture;

      [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
      internal Resources()
      {
      }

      /// <summary>
      ///   Returns the cached ResourceManager instance used by this class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
      internal static global::System.Resources.ResourceManager ResourceManager
      {
         get
         {
            if (object.ReferenceEquals(resourceMan, null))
            {
               global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockAnalyzerApp.Properties.Resources", typeof(Resources).Assembly);
               resourceMan = temp;
            }
            return resourceMan;
         }
      }

      /// <summary>
      ///   Overrides the current thread's CurrentUICulture property for all
      ///   resource lookups using this strongly typed resource class.
      /// </summary>
      [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
      internal static global::System.Globalization.CultureInfo Culture
      {
         get
         {
            return resourceCulture;
         }
         set
         {
            resourceCulture = value;
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap AddFolder
      {
         get
         {
            object obj = ResourceManager.GetObject("AddFolder", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap AddItem
      {
         get
         {
            object obj = ResourceManager.GetObject("AddItem", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap AddLine
      {
         get
         {
            object obj = ResourceManager.GetObject("AddLine", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap AddSarex
      {
         get
         {
            object obj = ResourceManager.GetObject("AddSarex", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap AddSegment
      {
         get
         {
            object obj = ResourceManager.GetObject("AddSegment", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap AddSemiLine
      {
         get
         {
            object obj = ResourceManager.GetObject("AddSemiLine", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap AddToReport
      {
         get
         {
            object obj = ResourceManager.GetObject("AddToReport", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Backward_icon
      {
         get
         {
            object obj = ResourceManager.GetObject("Backward_icon", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Camera
      {
         get
         {
            object obj = ResourceManager.GetObject("Camera", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Chart
      {
         get
         {
            object obj = ResourceManager.GetObject("Chart", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Comment
      {
         get
         {
            object obj = ResourceManager.GetObject("Comment", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap CopyLine
      {
         get
         {
            object obj = ResourceManager.GetObject("CopyLine", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Curve
      {
         get
         {
            object obj = ResourceManager.GetObject("Curve", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap cutLine
      {
         get
         {
            object obj = ResourceManager.GetObject("cutLine", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Decorator
      {
         get
         {
            object obj = ResourceManager.GetObject("Decorator", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Delete
      {
         get
         {
            object obj = ResourceManager.GetObject("Delete", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap DeleteTheme
      {
         get
         {
            object obj = ResourceManager.GetObject("DeleteTheme", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap EditPage
      {
         get
         {
            object obj = ResourceManager.GetObject("EditPage", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap EMail
      {
         get
         {
            object obj = ResourceManager.GetObject("EMail", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap FanLines
      {
         get
         {
            object obj = ResourceManager.GetObject("FanLines", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Forward_icon
      {
         get
         {
            object obj = ResourceManager.GetObject("Forward_icon", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap gear
      {
         get
         {
            object obj = ResourceManager.GetObject("gear", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Line
      {
         get
         {
            object obj = ResourceManager.GetObject("Line", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Log
      {
         get
         {
            object obj = ResourceManager.GetObject("Log", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Magnet
      {
         get
         {
            object obj = ResourceManager.GetObject("Magnet", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap magnet_pencil
      {
         get
         {
            object obj = ResourceManager.GetObject("magnet_pencil", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap NewAnalysis
      {
         get
         {
            object obj = ResourceManager.GetObject("NewAnalysis", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Notepad
      {
         get
         {
            object obj = ResourceManager.GetObject("Notepad", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap OpenAnalysis
      {
         get
         {
            object obj = ResourceManager.GetObject("OpenAnalysis", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Options
      {
         get
         {
            object obj = ResourceManager.GetObject("Options", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Paint
      {
         get
         {
            object obj = ResourceManager.GetObject("Paint", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap PaintBar
      {
         get
         {
            object obj = ResourceManager.GetObject("PaintBar", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap redo
      {
         get
         {
            object obj = ResourceManager.GetObject("redo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Reload
      {
         get
         {
            object obj = ResourceManager.GetObject("Reload", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap SaveAnalysis
      {
         get
         {
            object obj = ResourceManager.GetObject("SaveAnalysis", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap SaveAnalysisAs
      {
         get
         {
            object obj = ResourceManager.GetObject("SaveAnalysisAs", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap SaveTheme
      {
         get
         {
            object obj = ResourceManager.GetObject("SaveTheme", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap ScrollLeft
      {
         get
         {
            object obj = ResourceManager.GetObject("ScrollLeft", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap ScrollRight
      {
         get
         {
            object obj = ResourceManager.GetObject("ScrollRight", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap SetDefaultTheme
      {
         get
         {
            object obj = ResourceManager.GetObject("SetDefaultTheme", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap SR
      {
         get
         {
            object obj = ResourceManager.GetObject("SR", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap trail
      {
         get
         {
            object obj = ResourceManager.GetObject("trail", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap trashcan
      {
         get
         {
            object obj = ResourceManager.GetObject("trashcan", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap TrashLine
      {
         get
         {
            object obj = ResourceManager.GetObject("TrashLine", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap undo
      {
         get
         {
            object obj = ResourceManager.GetObject("undo", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap VolumeHistogram
      {
         get
         {
            object obj = ResourceManager.GetObject("VolumeHistogram", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap Wizard
      {
         get
         {
            object obj = ResourceManager.GetObject("Wizard", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap ZoomIn
      {
         get
         {
            object obj = ResourceManager.GetObject("ZoomIn", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }

      /// <summary>
      ///   Looks up a localized resource of type System.Drawing.Bitmap.
      /// </summary>
      internal static System.Drawing.Bitmap ZoomOut
      {
         get
         {
            object obj = ResourceManager.GetObject("ZoomOut", resourceCulture);
            return ((System.Drawing.Bitmap)(obj));
         }
      }
   }
}
