using System;

public class Fundamentals
{
    public int totalCount { get; set; }
    public Hit[] hits { get; set; }
}
public class Hit
{
    public int pair_ID { get; set; }
    public string stock_symbol { get; set; }
    public int parent_pair_ID { get; set; }
    public int canonical_to_pair_id { get; set; }
    public int override_country_ID { get; set; }
    public float eq_pe_ratio { get; set; }
    public string eq_pe_ratio_eu { get; set; }
}

public class Hit2
{
    public int pair_ID { get; set; }
    public string stock_symbol { get; set; }
    public int parent_pair_ID { get; set; }
    public int canonical_to_pair_id { get; set; }
    public int override_country_ID { get; set; }
    public float eq_pe_ratio { get; set; }
    public string eq_pe_ratio_eu { get; set; }
    public long eq_market_cap { get; set; }
    public string eq_market_cap_eu { get; set; }
    public float eq_one_year_return { get; set; }
    public string eq_one_year_return_eu { get; set; }
    public float eq_dividend { get; set; }
    public string eq_dividend_eu { get; set; }
    public float eq_eps { get; set; }
    public string eq_eps_eu { get; set; }
    public float eq_beta { get; set; }
    public string eq_beta_eu { get; set; }
    public long eq_revenue { get; set; }
    public string eq_revenue_eu { get; set; }
    public int exchange_ID { get; set; }
    public string security_type { get; set; }
    public string eq_pe_ratio_frmt { get; set; }
    public string eq_market_cap_frmt { get; set; }
    public string eq_one_year_return_frmt { get; set; }
    public string eq_dividend_frmt { get; set; }
    public string eq_eps_frmt { get; set; }
    public string eq_beta_frmt { get; set; }
    public string eq_revenue_frmt { get; set; }
    public string a1fcf { get; set; }
    public string a1fcf_eu { get; set; }
    public string a1fcf_us { get; set; }
    public string aastturn { get; set; }
    public string aastturn_eu { get; set; }
    public string aastturn_us { get; set; }
    public string abepsxclxo { get; set; }
    public string abepsxclxo_eu { get; set; }
    public string abepsxclxo_us { get; set; }
    public string abvps { get; set; }
    public string abvps_eu { get; set; }
    public string abvps_us { get; set; }
    public string acfshr { get; set; }
    public string acfshr_eu { get; set; }
    public string acfshr_us { get; set; }
    public string acshps { get; set; }
    public string acshps_eu { get; set; }
    public string acshps_us { get; set; }
    public string acurratio { get; set; }
    public string acurratio_eu { get; set; }
    public string acurratio_us { get; set; }
    public string adiv5yavg { get; set; }
    public string adiv5yavg_eu { get; set; }
    public string adiv5yavg_us { get; set; }
    public string aebitd { get; set; }
    public string aebitd_eu { get; set; }
    public string aebitd_us { get; set; }
    public string aebt { get; set; }
    public string aebt_eu { get; set; }
    public string aebt_us { get; set; }
    public string aebtnorm { get; set; }
    public string aebtnorm_eu { get; set; }
    public string aebtnorm_us { get; set; }
    public string aepsinclxo { get; set; }
    public string aepsinclxo_eu { get; set; }
    public string aepsinclxo_us { get; set; }
    public string aepsxclxor { get; set; }
    public string aepsxclxor_eu { get; set; }
    public string aepsxclxor_us { get; set; }
    public string agrosmgn { get; set; }
    public string agrosmgn_eu { get; set; }
    public string agrosmgn_us { get; set; }
    public string aintcov { get; set; }
    public string aintcov_eu { get; set; }
    public string aintcov_us { get; set; }
    public string ainvturn { get; set; }
    public string ainvturn_eu { get; set; }
    public string ainvturn_us { get; set; }
    public string altd2eq { get; set; }
    public string altd2eq_eu { get; set; }
    public string altd2eq_us { get; set; }
    public string aniac { get; set; }
    public string aniac_eu { get; set; }
    public string aniac_us { get; set; }
    public string aniacnorm { get; set; }
    public string aniacnorm_eu { get; set; }
    public string aniacnorm_us { get; set; }
    public string aniperemp { get; set; }
    public string aniperemp_eu { get; set; }
    public string aniperemp_us { get; set; }
    public string anpmgnpct { get; set; }
    public string anpmgnpct_eu { get; set; }
    public string anpmgnpct_us { get; set; }
    public string aopmgnpct { get; set; }
    public string aopmgnpct_eu { get; set; }
    public string aopmgnpct_us { get; set; }
    public string apayratio { get; set; }
    public string apayratio_eu { get; set; }
    public string apayratio_us { get; set; }
    public string apeexclxor { get; set; }
    public string apeexclxor_eu { get; set; }
    public string apeexclxor_us { get; set; }
    public string apenorm { get; set; }
    public string apenorm_eu { get; set; }
    public string apenorm_us { get; set; }
    public string apr2rev { get; set; }
    public string apr2rev_eu { get; set; }
    public string apr2rev_us { get; set; }
    public string apr2tanbk { get; set; }
    public string apr2tanbk_eu { get; set; }
    public string apr2tanbk_us { get; set; }
    public string aprfcfps { get; set; }
    public float aprfcfps_us { get; set; }
    public string aprice2bk { get; set; }
    public string aprice2bk_eu { get; set; }
    public string aprice2bk_us { get; set; }
    public string aptmgnpct { get; set; }
    public string aptmgnpct_eu { get; set; }
    public string aptmgnpct_us { get; set; }
    public string aquickrati { get; set; }
    public string aquickrati_eu { get; set; }
    public string aquickrati_us { get; set; }
    public string arecturn { get; set; }
    public string arecturn_eu { get; set; }
    public string arecturn_us { get; set; }
    public string arevperemp { get; set; }
    public string arevperemp_eu { get; set; }
    public string arevperemp_us { get; set; }
    public string arevps { get; set; }
    public string arevps_eu { get; set; }
    public string arevps_us { get; set; }
    public string aroa5yavg { get; set; }
    public string aroa5yavg_eu { get; set; }
    public string aroa5yavg_us { get; set; }
    public string aroapct { get; set; }
    public string aroapct_eu { get; set; }
    public string aroapct_us { get; set; }
    public string aroe5yavg { get; set; }
    public string aroe5yavg_eu { get; set; }
    public string aroe5yavg_us { get; set; }
    public string aroepct { get; set; }
    public string aroepct_eu { get; set; }
    public string aroepct_us { get; set; }
    public string aroi5yravg { get; set; }
    public string aroi5yravg_eu { get; set; }
    public string aroi5yravg_us { get; set; }
    public string aroipct { get; set; }
    public string aroipct_eu { get; set; }
    public string aroipct_us { get; set; }
    public string atanbvps { get; set; }
    public string atanbvps_eu { get; set; }
    public string atanbvps_us { get; set; }
    public string atotd2eq { get; set; }
    public string atotd2eq_eu { get; set; }
    public string atotd2eq_us { get; set; }
    public string bvtrendgr { get; set; }
    public string bvtrendgr_eu { get; set; }
    public string bvtrendgr_us { get; set; }
    public string country_id { get; set; }
    public string csptrendgr { get; set; }
    public string csptrendgr_eu { get; set; }
    public float csptrendgr_us { get; set; }
    public string divgrpct { get; set; }
    public float divgrpct_us { get; set; }
    public string divyield_curttm { get; set; }
    public string divyield_curttm_eu { get; set; }
    public string divyield_curttm_us { get; set; }
    public string ebitda_ayr5cagr { get; set; }
    public string ebitda_ayr5cagr_eu { get; set; }
    public string ebitda_ayr5cagr_us { get; set; }
    public string ebitda_ttmy5cagr { get; set; }
    public string ebitda_ttmy5cagr_eu { get; set; }
    public string ebitda_ttmy5cagr_us { get; set; }
    public string epschngyr { get; set; }
    public string epschngyr_eu { get; set; }
    public float epschngyr_us { get; set; }
    public string epsgrpct { get; set; }
    public string epsgrpct_eu { get; set; }
    public string epsgrpct_us { get; set; }
    public string epstrendgr { get; set; }
    public string epstrendgr_eu { get; set; }
    public float epstrendgr_us { get; set; }
    public string ev2fcf_cura { get; set; }
    public string ev2fcf_cura_eu { get; set; }
    public string ev2fcf_cura_us { get; set; }
    public string ev2fcf_curttm { get; set; }
    public string ev2fcf_curttm_eu { get; set; }
    public string ev2fcf_curttm_us { get; set; }
    public string focf_ayr5cagr { get; set; }
    public string focf_ayr5cagr_eu { get; set; }
    public string focf_ayr5cagr_us { get; set; }
    public string grosmgn5yr { get; set; }
    public float grosmgn5yr_us { get; set; }
    // public string industry_id { get; set; }
    public string margin5yr { get; set; }
    public float margin5yr_us { get; set; }
    public string mktcap { get; set; }
    public string mktcap_eu { get; set; }
    public string mktcap_us { get; set; }
    public string netdebt_a { get; set; }
    public string netdebt_a_eu { get; set; }
    public string netdebt_a_us { get; set; }
    public string npmtrendgr { get; set; }
    public string npmtrendgr_eu { get; set; }
    public string npmtrendgr_us { get; set; }
    public string opmgn5yr { get; set; }
    public float opmgn5yr_us { get; set; }
    public string pair_id { get; set; }
    public string pebexclxor { get; set; }
    public string pebexclxor_eu { get; set; }
    public string pebexclxor_us { get; set; }
    public string peexclxor { get; set; }
    public float peexclxor_us { get; set; }
    public string pr2tanbk { get; set; }
    public float pr2tanbk_us { get; set; }
    public string price2bk { get; set; }
    public float price2bk_us { get; set; }
    public string ptmgn5yr { get; set; }
    public float ptmgn5yr_us { get; set; }
    public string qbvps { get; set; }
    public string qbvps_eu { get; set; }
    public string qbvps_us { get; set; }
    public string qcshps { get; set; }
    public string qcshps_eu { get; set; }
    public string qcshps_us { get; set; }
    public string qquickrati { get; set; }
    public float qquickrati_us { get; set; }
    public string qtotd2eq { get; set; }
    public float qtotd2eq_us { get; set; }
    public string revchngyr { get; set; }
    public string revchngyr_eu { get; set; }
    public float revchngyr_us { get; set; }
    public string revgrpct { get; set; }
    public string revgrpct_eu { get; set; }
    public string revgrpct_us { get; set; }
    public string revps5ygr { get; set; }
    public string revps5ygr_eu { get; set; }
    public string revps5ygr_us { get; set; }
    public string revtrendgr { get; set; }
    public string revtrendgr_eu { get; set; }
    public float revtrendgr_us { get; set; }
    public string stld_ayr5cagr { get; set; }
    public string stld_ayr5cagr_eu { get; set; }
    public string stld_ayr5cagr_us { get; set; }
    public float ttmcfshr { get; set; }
    public string ttmcfshr_eu { get; set; }
    public string ttmcfshr_us { get; set; }
    public string ttmebitd { get; set; }
    public string ttmebitd_eu { get; set; }
    public string ttmebitd_us { get; set; }
    public string ttmebitdps { get; set; }
    public string ttmebitdps_eu { get; set; }
    public string ttmebitdps_us { get; set; }
    public string ttmebt { get; set; }
    public string ttmebt_eu { get; set; }
    public string ttmebt_us { get; set; }
    public string ttmepschg { get; set; }
    public string ttmepschg_eu { get; set; }
    public float ttmepschg_us { get; set; }
    public string ttmfcf { get; set; }
    public string ttmfcf_eu { get; set; }
    public string ttmfcf_us { get; set; }
    public string ttmfcfshr { get; set; }
    public string ttmfcfshr_eu { get; set; }
    public string ttmfcfshr_us { get; set; }
    public string ttmgrosmgn { get; set; }
    public float ttmgrosmgn_us { get; set; }
    public string ttmintcov { get; set; }
    public string ttmintcov_eu { get; set; }
    public string ttmintcov_us { get; set; }
    public string ttminvturn { get; set; }
    public string ttminvturn_eu { get; set; }
    public float ttminvturn_us { get; set; }
    public string ttmniac { get; set; }
    public string ttmniac_eu { get; set; }
    public string ttmniac_us { get; set; }
    public string ttmniperem { get; set; }
    public string ttmniperem_eu { get; set; }
    public float ttmniperem_us { get; set; }
    public string ttmnpmgn { get; set; }
    public float ttmnpmgn_us { get; set; }
    public string ttmopmgn { get; set; }
    public float ttmopmgn_us { get; set; }
    public string ttmpr2rev { get; set; }
    public float ttmpr2rev_us { get; set; }
    public string ttmprcfps { get; set; }
    public string ttmprcfps_eu { get; set; }
    public string ttmprcfps_us { get; set; }
    public string ttmprfcfps { get; set; }
    public float ttmprfcfps_us { get; set; }
    public string ttmptmgn { get; set; }
    public float ttmptmgn_us { get; set; }
    public string ttmrevchg { get; set; }
    public string ttmrevchg_eu { get; set; }
    public float ttmrevchg_us { get; set; }
    public string ttmrevpere { get; set; }
    public string ttmrevpere_eu { get; set; }
    public float ttmrevpere_us { get; set; }
    public string ttmrevps { get; set; }
    public string ttmrevps_eu { get; set; }
    public string ttmrevps_us { get; set; }
    public string ttmroapct { get; set; }
    public string ttmroapct_eu { get; set; }
    public string ttmroapct_us { get; set; }
    public string ttmroepct { get; set; }
    public string ttmroepct_eu { get; set; }
    public string ttmroepct_us { get; set; }
    public string ttmroipct { get; set; }
    public string ttmroipct_eu { get; set; }
    public string ttmroipct_us { get; set; }
    public string yield { get; set; }
    public string yield_us { get; set; }
    public string yld5yavg { get; set; }
    public float yld5yavg_us { get; set; }
    public string peexclxor_us_eu { get; set; }
    public string ttmpr2rev_us_eu { get; set; }
    public string aprfcfps_us_eu { get; set; }
    public string ttmprfcfps_us_eu { get; set; }
    public string price2bk_us_eu { get; set; }
    public string pr2tanbk_us_eu { get; set; }
    public string ttmgrosmgn_us_eu { get; set; }
    public string ttmopmgn_us_eu { get; set; }
    public string ttmnpmgn_us_eu { get; set; }
    public string yield_us_eu { get; set; }
    public string yld5yavg_us_eu { get; set; }
    public string divgrpct_us_eu { get; set; }
    public string grosmgn5yr_us_eu { get; set; }
    public string opmgn5yr_us_eu { get; set; }
    public string ttmptmgn_us_eu { get; set; }
    public string ptmgn5yr_us_eu { get; set; }
    public string margin5yr_us_eu { get; set; }
    public string qquickrati_us_eu { get; set; }
    public string qtotd2eq_us_eu { get; set; }
    public string epschngyr_us_eu { get; set; }
    public string ttmepschg_us_eu { get; set; }
    public string epstrendgr_us_eu { get; set; }
    public string revchngyr_us_eu { get; set; }
    public string ttmrevchg_us_eu { get; set; }
    public string revtrendgr_us_eu { get; set; }
    public string csptrendgr_us_eu { get; set; }
    public string ttminvturn_us_eu { get; set; }
    public string ttmrevpere_us_eu { get; set; }
    public string ttmniperem_us_eu { get; set; }
    public string peexclxor_us_frmt { get; set; }
    public string ttmpr2rev_us_frmt { get; set; }
    public string aprfcfps_us_frmt { get; set; }
    public string ttmprfcfps_us_frmt { get; set; }
    public string price2bk_us_frmt { get; set; }
    public string pr2tanbk_us_frmt { get; set; }
    public string ttmgrosmgn_us_frmt { get; set; }
    public string ttmopmgn_us_frmt { get; set; }
    public string ttmnpmgn_us_frmt { get; set; }
    public string yield_us_frmt { get; set; }
    public string yld5yavg_us_frmt { get; set; }
    public string divgrpct_us_frmt { get; set; }
    public string grosmgn5yr_us_frmt { get; set; }
    public string opmgn5yr_us_frmt { get; set; }
    public string ttmptmgn_us_frmt { get; set; }
    public string ptmgn5yr_us_frmt { get; set; }
    public string margin5yr_us_frmt { get; set; }
    public string qquickrati_us_frmt { get; set; }
    public string qtotd2eq_us_frmt { get; set; }
    public string epschngyr_us_frmt { get; set; }
    public string ttmepschg_us_frmt { get; set; }
    public string epstrendgr_us_frmt { get; set; }
    public string revchngyr_us_frmt { get; set; }
    public string ttmrevchg_us_frmt { get; set; }
    public string revtrendgr_us_frmt { get; set; }
    public string csptrendgr_us_frmt { get; set; }
    public string ttminvturn_us_frmt { get; set; }
    public string ttmrevpere_us_frmt { get; set; }
    public string ttmniperem_us_frmt { get; set; }
    public string beta { get; set; }
    public string beta_eu { get; set; }
    public string beta_us { get; set; }
    public string focf2rev_aavg5 { get; set; }
    public string focf2rev_aavg5_eu { get; set; }
    public string focf2rev_aavg5_us { get; set; }
    public string focf2rev_ttm { get; set; }
    public string focf2rev_ttm_eu { get; set; }
    public string focf2rev_ttm_us { get; set; }
    public string netdebt_i { get; set; }
    public string netdebt_i_eu { get; set; }
    public string netdebt_i_us { get; set; }
    public string peinclxor { get; set; }
    public string peinclxor_eu { get; set; }
    public string peinclxor_us { get; set; }
    public string qcurratio { get; set; }
    public float qcurratio_us { get; set; }
    public string qltd2eq { get; set; }
    public float qltd2eq_us { get; set; }
    public string qtanbvps { get; set; }
    public string qtanbvps_eu { get; set; }
    public string qtanbvps_us { get; set; }
    public string sharesout { get; set; }
    public string sharesout_eu { get; set; }
    public string sharesout_us { get; set; }
    public string tanbv_ayr5cagr { get; set; }
    public string tanbv_ayr5cagr_eu { get; set; }
    public string tanbv_ayr5cagr_us { get; set; }
    public string ttmastturn { get; set; }
    public string ttmastturn_eu { get; set; }
    public float ttmastturn_us { get; set; }
    public string ttmbepsxcl { get; set; }
    public string ttmbepsxcl_eu { get; set; }
    public string ttmbepsxcl_us { get; set; }
    public string ttmepsincx { get; set; }
    public string ttmepsincx_eu { get; set; }
    public string ttmepsincx_us { get; set; }
    public string ttmepsxclx { get; set; }
    public string ttmepsxclx_eu { get; set; }
    public string ttmepsxclx_us { get; set; }
    public string ttmpayrat { get; set; }
    public float ttmpayrat_us { get; set; }
    public string ttmpehigh { get; set; }
    public string ttmpehigh_eu { get; set; }
    public string ttmpehigh_us { get; set; }
    public string ttmpelow { get; set; }
    public string ttmpelow_eu { get; set; }
    public string ttmpelow_us { get; set; }
    public string ttmrecturn { get; set; }
    public string ttmrecturn_eu { get; set; }
    public float ttmrecturn_us { get; set; }
    public string vdes_ttm { get; set; }
    public string vdes_ttm_eu { get; set; }
    public string vdes_ttm_us { get; set; }
    public string ttmpayrat_us_eu { get; set; }
    public string qcurratio_us_eu { get; set; }
    public string qltd2eq_us_eu { get; set; }
    public string ttmastturn_us_eu { get; set; }
    public string ttmrecturn_us_eu { get; set; }
    public string ttmpayrat_us_frmt { get; set; }
    public string qcurratio_us_frmt { get; set; }
    public string qltd2eq_us_frmt { get; set; }
    public string ttmastturn_us_frmt { get; set; }
    public string ttmrecturn_us_frmt { get; set; }
    public float RSI { get; set; }
    public float STOCH { get; set; }
    public float CCI { get; set; }
    public float MACD { get; set; }
    public float ADX { get; set; }
    public float WilliamsR { get; set; }
    public float STOCHRSI { get; set; }
    public float ATR { get; set; }
    public float HL { get; set; }
    public float UO { get; set; }
    public float ROC { get; set; }
    public float BullBear { get; set; }
    public string tech_sum_300 { get; set; }
    public string tech_sum_300_Define { get; set; }
    public int tech_sum_300_Define_order_priority { get; set; }
    public string tech_sum_300_Color { get; set; }
    public string tech_sum_900 { get; set; }
    public string tech_sum_900_Define { get; set; }
    public int tech_sum_900_Define_order_priority { get; set; }
    public string tech_sum_900_Color { get; set; }
    public string tech_sum_1800 { get; set; }
    public string tech_sum_1800_Define { get; set; }
    public int tech_sum_1800_Define_order_priority { get; set; }
    public string tech_sum_1800_Color { get; set; }
    public string tech_sum_3600 { get; set; }
    public string tech_sum_3600_Define { get; set; }
    public int tech_sum_3600_Define_order_priority { get; set; }
    public string tech_sum_3600_Color { get; set; }
    public string tech_sum_18000 { get; set; }
    public string tech_sum_18000_Define { get; set; }
    public int tech_sum_18000_Define_order_priority { get; set; }
    public string tech_sum_18000_Color { get; set; }
    public string tech_sum_86400 { get; set; }
    public string tech_sum_86400_Define { get; set; }
    public int tech_sum_86400_Define_order_priority { get; set; }
    public string tech_sum_86400_Color { get; set; }
    public string tech_sum_week { get; set; }
    public string tech_sum_week_Define { get; set; }
    public int tech_sum_week_Define_order_priority { get; set; }
    public string tech_sum_week_Color { get; set; }
    public string tech_sum_month { get; set; }
    public string tech_sum_month_Define { get; set; }
    public int tech_sum_month_Define_order_priority { get; set; }
    public string tech_sum_month_Color { get; set; }
    public string RSI_eu { get; set; }
    public string STOCH_eu { get; set; }
    public string CCI_eu { get; set; }
    public string MACD_eu { get; set; }
    public string ADX_eu { get; set; }
    public string WilliamsR_eu { get; set; }
    public string STOCHRSI_eu { get; set; }
    public string ATR_eu { get; set; }
    public string HL_eu { get; set; }
    public string UO_eu { get; set; }
    public string ROC_eu { get; set; }
    public string BullBear_eu { get; set; }
    public float month_change { get; set; }
    public string month_change_eu { get; set; }
    public float ytd { get; set; }
    public float week { get; set; }
    public float month { get; set; }
    public float year { get; set; }
    public float _3year { get; set; }
    public string ytd_eu { get; set; }
    public string week_eu { get; set; }
    public string month_eu { get; set; }
    public string year_eu { get; set; }
    public string _3year_eu { get; set; }
    public int sector_id { get; set; }
    public int avg_volume { get; set; }
    public string avg_volume_eu { get; set; }
    public float pair_change_percent { get; set; }
    public string pair_change_percent_eu { get; set; }
    public float a52_week_high { get; set; }
    public string a52_week_high_eu { get; set; }
    public float a52_week_low { get; set; }
    public string a52_week_low_eu { get; set; }
    public int turnover_volume { get; set; }
    public string turnover_volume_eu { get; set; }
    public float last { get; set; }
    public string last_eu { get; set; }
    public string last_frmt { get; set; }
    public string avg_volume_frmt { get; set; }
    public string pair_change_percent_frmt { get; set; }
    public string a52_week_high_frmt { get; set; }
    public string a52_week_low_frmt { get; set; }
    public string turnover_volume_frmt { get; set; }
    public float a52_week_high_diff { get; set; }
    public string a52_week_high_diff_eu { get; set; }
    public float a52_week_low_diff { get; set; }
    public string a52_week_low_diff_eu { get; set; }
    public string exchange_trans { get; set; }
    public string name_trans { get; set; }
    public string sector_trans { get; set; }
    public string industry_trans { get; set; }
    public Viewdata viewData { get; set; }
    public string tech_sum_300_constant { get; set; }
    public string tech_sum_900_constant { get; set; }
    public string tech_sum_1800_constant { get; set; }
    public string tech_sum_3600_constant { get; set; }
    public string tech_sum_18000_constant { get; set; }
    public string tech_sum_86400_constant { get; set; }
    public string tech_sum_week_constant { get; set; }
    public string tech_sum_month_constant { get; set; }
    public float daily { get; set; }
    public string daily_eu { get; set; }
    public string daily_frmt { get; set; }
    public string projepsq { get; set; }
    public string projepsq_eu { get; set; }
    public string projepsq_us { get; set; }
}

public class Viewdata
{
    public string flag { get; set; }
    public string symbol { get; set; }
    public string link { get; set; }
    public string name { get; set; }
}

