//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockAnalyzerApp.CustomControl.IndicatorDlgs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IndicatorDlgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IndicatorDlgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockAnalyzerApp.CustomControl.IndicatorDlgs.IndicatorDlgs", typeof(IndicatorDlgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True/False.
        /// </summary>
        internal static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decorator parameters.
        /// </summary>
        internal static string DecoratorParam {
            get {
                return ResourceManager.GetString("DecoratorParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input, type either &quot;True&quot; or &quot;False&quot;.
        /// </summary>
        internal static string ExpectedIndicatorParameterBool {
            get {
                return ResourceManager.GetString("ExpectedIndicatorParameterBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input, $type exptected between $min and $max.
        /// </summary>
        internal static string ExpectedIndicatorParameterRange {
            get {
                return ResourceManager.GetString("ExpectedIndicatorParameterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input, Not in supported value list.
        /// </summary>
        internal static string ExpectedIndicatorParameterStringList {
            get {
                return ResourceManager.GetString("ExpectedIndicatorParameterStringList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicator parameters.
        /// </summary>
        internal static string IndicatorParam {
            get {
                return ResourceManager.GetString("IndicatorParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        internal static string Int32 {
            get {
                return ResourceManager.GetString("Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameter.
        /// </summary>
        internal static string InvalidIndicatorParameter {
            get {
                return ResourceManager.GetString("InvalidIndicatorParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paint bar  parameters.
        /// </summary>
        internal static string PaintBarParam {
            get {
                return ResourceManager.GetString("PaintBarParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trail stop parameters.
        /// </summary>
        internal static string TrailStopParam {
            get {
                return ResourceManager.GetString("TrailStopParam", resourceCulture);
            }
        }
    }
}
